services:
  backend:
    build:
      context: ./backend
    container_name: campus-connect-backend-compose
    ports:
      - "4002:4000"
    env_file:
      - backend-test.env

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:4002/api
    container_name: campus-connect-frontend-compose
    ports:
      - "3002:3000"
    depends_on:
      - backend