apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          env:
            - name: MONGODB_URI
              value: {{ .Values.backend.mongodbUri | quote }}
            - name: NODE_ENV
              value: {{ .Values.backend.nodeEnv | quote }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: campus-connect-secrets
                  key: JWT_SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      nodePort: {{ .Values.backend.service.nodePort }}
  type: {{ .Values.backend.service.type }}