apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongodb.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mongodb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.name }}
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.mongodb.containerPort }}
          volumeMounts:
            - name: mongodb-data
              mountPath: {{ .Values.mongodb.storage.mountPath }}
      volumes:
        - name: mongodb-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.mongodb.name }}
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.targetPort }}
  type: {{ .Values.mongodb.service.type }}